### ISSUE TITLE
无法从设置路径启动游戏&无法启动已安装的BettterGI

### ISSUE THREAD

**Issue by Andrea-lyz** [GenshinMatrix/Fischless#1]
### Problem Description | 问题描述

无法从设置的路径启动游戏
插件部分无法识别到已安装的BettterGI

### Reproduction steps | 复现步骤

添加账号-设定-勾选游戏路径-"E:\Genshin Impact\YuanShen.exe"
插件-BettterGI-设置按钮

### Screenshot | 截图

![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/529a475f-7a78-4042-aa48-1b98bb88d76b)
![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/e9f1a2fe-aeb2-480a-8492-57512e7d162e)
![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/08d794d3-fbe7-42db-a71e-bea6532770f4)
![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/7cddee51-b01b-4f5b-b5a9-12d085a9d1a6)

### System version | 系统版本

Windows 11 23H2

### Fischless Version | 永夜真梦版本

更新到最新版本后问题反馈

### Log | 日志

[Fischless_20231125.log](https://github.com/GenshinMatrix/Fischless/files/13462763/Fischless_20231125.log)

**Comment by huiyadanli** [comment]
bettergi链接，在下个版本才会有。当前版本还没这个

**Comment by Andrea-lyz** [comment]
> bettergi链接，在下个版本才会有。当前版本还没这个

好的，感谢
那这个启动问题请教一下如何解决，原神是从starward启动器直接安装的

**Comment by emako** [comment]
![image](https://github.com/GenshinMatrix/Fischless/assets/24737061/c767089b-cbe4-4d94-b3ed-629d2213555d)

**Comment by huiyadanli** [comment]
0.16 已经发布

https://github.com/babalae/better-genshin-impact/releases

**Comment by Andrea-lyz** [comment]
@emako 
你好，游戏路径启动问题似乎没有解决

**Comment by emako** [comment]
> @emako 你好，游戏路径启动问题似乎没有解决

[v0.3.8](https://github.com/GenshinMatrix/Fischless/releases/tag/v0.3.8)解决路径问题
