### ISSUE TITLE
v0.3.8依然无法启动游戏

### ISSUE THREAD

**Issue by Andrea-lyz** [GenshinMatrix/Fischless#2]
### Problem Description | 问题描述

如标题
显示原神未安装

### Reproduction steps | 复现步骤

添加账号-设定-勾选游戏路径-"E:\Genshin Impact\YuanShen.exe"

### Screenshot | 截图

![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/fc2d8559-948d-463a-a429-750c4ee619b6)

### System version | 系统版本

Windows 11 23H2

### Fischless Version | 永夜真梦版本

更新到最新版本后问题反馈

### Log | 日志

[Fischless_20231127.log](https://github.com/GenshinMatrix/Fischless/files/13476116/Fischless_20231127.log)

### Remarks | 备注

用户配置（删除Prod并修改为txt上传）
[config.txt](https://github.com/GenshinMatrix/Fischless/files/13476144/config.txt)

**Comment by emako** [comment]
正常目录结构不是`Genshin Impact\Genshin Impact Game\YuanShen.exe`吗，`E:\Genshin Impact\YuanShen.exe`这怎么弄出来的？

**Comment by Andrea-lyz** [comment]
> 正常目录结构不是`Genshin Impact\Genshin Impact Game\YuanShen.exe`吗，`E:\Genshin Impact\YuanShen.exe`这怎么弄出来的？

从starward下载的话就这样，少一层文件夹😂

**Comment by Andrea-lyz** [comment]
![image](https://github.com/GenshinMatrix/Fischless/assets/52863141/2fbd2317-6b5f-461c-93a5-585569a1cae3)
@emako 目录结构是这样的

**Comment by emako** [comment]
已知问题是启动时做了多余的注册表判断导致，下版本修复。
~~目前版本你可以先使用注册表修复插件（需要管理员启动Fischless）。~~
注册表修复采用严格遵守官方的路径，目前也无法适配starward~

**Comment by emako** [comment]
可尝试获取修复
> https://github.com/GenshinMatrix/Fischless/releases/tag/v0.3.9

**Comment by Andrea-lyz** [comment]
> 可尝试获取修复
> 
> > https://github.com/GenshinMatrix/Fischless/releases/tag/v0.3.9

感谢，尝试后已能够正常启动
