### ISSUE TITLE
[bug] FPS解锁工具失效

### ISSUE THREAD

**Issue by Andrea-lyz** [GenshinMatrix/Fischless#3]
- 系统环境 / System Environment：
版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2024/‎2/‎24
操作系统版本	22631.3155
体验	Windows Feature Experience Pack 1000.22684.1000.0

- 永夜真梦版本号 / Fischless Version：
v0.4.2

- 问题描述 / Description of the issue：
FPS解锁工具失效

- 复现步骤 / Reproduction steps：
设定-勾选解锁帧率-填写120-关闭-关闭功能配置窗口后再打开设定自动变回60-启动游戏不生效
后续手动记事本修改配置文件FPS120-启动游戏不生效
已尝试删除配置文件并重新安装Fischless 依旧无效
尝试其他[解锁工具](https://github.com/sefinek24/Genshin-FPS-Unlocker/releases/tag/v3.2.0.1)，成功解锁帧率

**Comment by emako** [comment]
旧方法失效了，后续更新

**Comment by emako** [comment]
https://github.com/GenshinMatrix/Fischless/releases/tag/v0.4.3
